name: Build Repo Mod DLLs

on:
  push:
    branches: [ "main" ]
  
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Build Mod (Debug & Release)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 6.0 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Debug
        run: dotnet build --configuration Debug --no-restore

      - name: Build Release
        run: dotnet build --configuration Release --no-restore

      - name: Upload Debug Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Debug-Build
          path: 'bin/Debug/*/shared_upgrades.dll'
          if-no-files-found: error

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release-Build
          path: 'bin/Release/*/shared_upgrades.dll'
          if-no-files-found: error
